<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>BELORIZONTINO - O melhor de BH voc&ecirc; encontra aqui</title>
<link href="<?php $this->asset('estilo.css','css'); ?>" rel="stylesheet" type="text/css" />
<link href="<?php $this->asset('menu.css','css'); ?>" rel="stylesheet" type="text/css" />
<link href="<?php $this->asset('nav.css','css'); ?>" rel="stylesheet" type="text/css" />

<?php if($this->currentController == 'contact') : ?>
<script src="<?php $this->asset('SpryValidationTextField.js','SpryAssets'); ?>" type="text/javascript"></script>
<script src="<?php $this->asset('SpryValidationTextarea.js','SpryAssets'); ?>" type="text/javascript"></script>
<link href="<?php $this->asset('SpryValidationTextField.css','SpryAssets'); ?>" rel="stylesheet" type="text/css" />
<link href="<?php $this->asset('SpryValidationTextarea.css','SpryAssets'); ?>" rel="stylesheet" type="text/css" />
<?php endif; ?>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-12375493-24']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

<?php echo $this->alerts(); ?>

</head>

<body>
<div id="header">
  <div id="topo">
    <div id="logo"><a href="<?php echo $this->baseUrl('/'); ?>"><img src="<?php $this->asset('logo.png','imagens'); ?>" width="348" height="115" border="0" /></a></div>
    <div id="menu">
         <?php echo $this->render('menu.phtml'); ?>    
    </div>
  </div>
</div>