<?php

/**
 * @see Zend_View_Helper_Abstract
 */
require_once 'Zend/View/Helper/Abstract.php';

/**
 * The View Helper for show alerts with messages stored in FlashMessenger Action Helper
 * 
 * @category Helpers
 * @package App/Plugins
 * @subpackage Helpers
 * @author Lucas Mendes de Freitas (devsdmf)
 * @since 2012
 * @license http://www.devsdmf.net/license/general.txt
 * @copyright devSDMF Software Development (c)
 *
 */

class Zend_View_Helper_Alerts extends Zend_View_Helper_Abstract
{
	/**
	 * The script generated by object
	 * 
	 * @var string
	 */
	protected $_script = null;
	/**
	 * Method to render the script
	 * 
	 * @return string
	 */
	function alerts()
	{
		if($this->view->flashMessengerAlerts != null)
		{
			$this->_script = '<script type="text/javascript">';
			foreach($this->view->flashMessengerAlerts as $alert) 
			{
				$this->_script .= 'alert("' . $alert . '");' . PHP_EOL;
			}
			$this->_script .= '</script>';
		}
		
		return $this->_script;
	}
}