<?php echo $this->render('header.phtml'); ?>

<div id="container-blog">
  <div id="text-blog">
    <h1>Parceiros<br />
      <br />
    </h1>
    <table width="804" border="0" cellspacing="10">
      <tr>
        <td width="220" height="100"><img src="<?php $this->asset('aplus.jpg','imagens/parceiros'); ?>" width="221" height="100" /></td>
        <td width="220"><img src="<?php $this->asset('casa.jpg','imagens/parceiros'); ?>" width="221" height="100" /></td>
        <td width="220"><img src="<?php $this->asset('dermoclin.jpg','imagens/parceiros'); ?>" width="221" height="100" /></td>
      </tr>
      <tr>
        <td height="100"><img src="<?php $this->asset('espro.jpg','imagens/parceiros'); ?>" width="221" height="100" /></td>
        <td><img src="<?php $this->asset('guia.jpg','imagens/parceiros'); ?>" width="221" height="100" /></td>
        <td><img src="<?php $this->asset('geraldin.jpg','imagens/parceiros'); ?>" width="221" height="100" /></td>
      </tr>
      <tr>
        <td height="100"><img src="<?php $this->asset('paladar.jpg','imagens/parceiros'); ?>" width="221" height="100" /></td>
        <td><img src="<?php $this->asset('ravi.jpg','imagens/parceiros'); ?>" width="221" height="100" /></td>
        <td><img src="<?php $this->asset('santa.jpg','imagens/parceiros'); ?>" width="219" height="100" /></td>
      </tr>
      <tr>
        <td><img src="<?php $this->asset('vitrine.jpg','imagens/parceiros'); ?>" width="219" height="100" /></td>
        <td><img src="<?php $this->asset('bhburger.jpg','imagens/parceiros'); ?>" width="219" height="100" /></td>
        <td><img src="<?php $this->asset('fisioderme.jpg','imagens/parceiros'); ?>" width="221" height="100" /></td>
      </tr>
      <tr>
        <td><img src="<?php $this->asset('ghfight.jpg','imagens/parceiros'); ?>" width="221" height="100" /></td>
        <td><img src="<?php $this->asset('ghstudio.jpg','imagens/parceiros'); ?>" width="221" height="100" /></td>
        <td><img src="<?php $this->asset('palia.jpg','imagens/parceiros'); ?>" width="221" height="100" /></td>
      </tr>
      <tr>
        <td><img src="<?php $this->asset('saude.jpg','imagens/parceiros'); ?>" width="221" height="100" /></td>
        <td><img src="<?php $this->asset('conceito.jpg','imagens/parceiros'); ?>" width="220" height="100" /></td>
        <td><img src="<?php $this->asset('park.jpg','imagens/parceiros'); ?>" width="220" height="100" /></td>
      </tr>
    </table>
    <span class="colunista"><br />
    </span>
    <h2><br />
  <br />

<br />
<br />
<br />
  </h2>
  </div>
</div>

<?php echo $this->render('footer.phtml'); ?>