<?php echo $this->render('header.phtml'); ?>

<div id="container">
  <div id="col-left">
    <h1>Jornal Belorizontino</h1>
    <h2><br />
      O jornal comercial BELORIZONTINO, nasceu da visão de seus fundadores, José Milton Bethônico e Breno Borges, para servir como meio de ligação comunicativa entre as empresas e seus públicos.

    <br />
    <br />
    Nossa veiculação será progressiva, com a finalidade de alcançar toda a Belo Horizonte e Região Metropolitana, proporcionando um intercambio comercial entre regiões, com a finalidade de sempre alcançar mais consumidores.

    <br />
    <br />
    Constituímos uma equipe de gestão composta por especialistas experientes, que nos permite obter níveis de qualidade pouco habituais em publicações deste tipo, seja ela na parte de diagramação, design, impressão, correção, como também com excelentes parcerias, tendo sempre como objetivo desenvolver o produto que melhor atenda às necessidades de sua empresa.</h2>
  <span class="copy"><br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  </span>
  </div>
    <div id="col-right">
    <h1>Alvos</h1>
    <h2><br />
    1 – Garantir a entrega do produto;
    <br />
    2 – Influenciar diretamente em resultados positivos aos nossos associados;
    <br />
    3 – Excelência;
    <br />
    4 – Pontualidade.
    </h2>
    
    <h1><br />
      Missão</h1>
    <h2>   Divulgar a marca do cliente, sempre com compromisso, ética, sofisticação, qualidade e modernidade.
    </h2>
    
        <h1><br />
      Tiragem</h1>
    <h2>30.000 exemplares</h2>
    
  </div>
</div>

<?php echo $this->render('footer.phtml'); ?>